
black_list = [
	"25th percentile length URIs (subject)",
	"25th percentile length URIs (predicate)",
	"25th percentile throughput",
	"25th percentile latency",
	"25th percentile length URIs (object)",
	"75th percentile length URIs (subject)",
	"75th percentile length URIs (predicate)",
	"75th percentile length URIs (object)",
	"75th percentile throughput",
	"75th percentile latency",
	"MinTPNoOff",
	"MaxTPNoOff",
	"Min length URIs (subject)",
	"Max length URIs (subject)",
	"Min length URIs (predicate)",
	"Max length URIs (object)",
	"Min length URIs (object)",
	"Minimum latency",
	"Maximum latency",
	"Minimum throughput",
	"Maximum throughput",
	" Percentage of triples with labels",
    "Percentage of data updated",
]